CREATE DATABASE  IF NOT EXISTS SEGURIDAD;
USE SEGURIDAD;


DROP TABLE IF EXISTS USUARIOS;
CREATE TABLE USUARIOS (
  IDUSUARIO 		int(5) NOT NULL AUTO_INCREMENT,
  USUARIO 			varchar(10) NOT NULL,
  PASSWORD 		varchar(100) NOT NULL,
  PRIMARY KEY (IDUSUARIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
