CREATE DATABASE  IF NOT EXISTS SESIONES02;
USE SESIONES02;

DROP TABLE IF EXISTS USUARIOS;
CREATE TABLE USUARIOS (
	  IDUSUARIO 	int(3) NOT NULL AUTO_INCREMENT,
	  USUARIO 		varchar(20) NOT NULL,
	  PASSWORD 	varchar(10) NOT NULL,
  PRIMARY KEY (IDUSUARIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS JUGADAS;
CREATE TABLE JUGADAS (
	  ID					 		int(3) NOT NULL AUTO_INCREMENT,
	  USUARIO 			varchar(20) NOT NULL,
	  NJUGADA 			int(3) NOT NULL,
	  JUGADA				int(3) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES USUARIOS WRITE;
INSERT INTO USUARIOS VALUES (1,'JORGE','666666'),(2,'PEPE','123456'),(3,'JUAN','MIRINDA');
UNLOCK TABLES;