CREATE DATABASE  IF NOT EXISTS examen;
USE examen;

DROP TABLE IF EXISTS facturas;
CREATE TABLE facturas
(
  NFACTURA			varchar(10) NOT NULL,
  TOTAL					int(5) NOT NULL,
  PRIMARY KEY (NFACTURA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES facturas WRITE;
INSERT INTO facturas VALUES ('FACTURA20',200),('FACTURA30',300),('FACTURA40',400),('FACTURA80',800);
UNLOCK TABLES;
